import { useState, useEffect } from "react"

export type Language = "en" | "zh"

export const translations = {
  en: {
    appName: "PromptInk",
    welcome: "What image would you like to create?",
    welcomeSubtitle: "Describe your vision and I'll generate a unique image using DALL-E 3",
    placeholder: "Describe the image you want to create...",
    placeholderListening: "Listening...",
    generate: "Generate",
    generating: "Generating...",
    generatingImage: "Generating image",
    newChat: "New chat",
    openFullSize: "Open Full Size",
    syncToTrmnl: "Sync to TRMNL",
    syncing: "Syncing...",
    syncSuccess: "Synced!",
    footer: "PromptInk uses DALL-E 3 to generate images. Press Enter to send, Shift+Enter for new line.",
    you: "You",
    assistant: "PromptInk",
    suggestions: [
      "A serene Japanese garden with cherry blossoms at sunset",
      "A futuristic city with flying cars and neon lights",
      "A cozy cabin in the mountains during winter",
      "An underwater palace with bioluminescent creatures",
    ],
    errorPrefix: "Error:",
    defaultImageMessage: "Here's your generated image:",
    logout: "Logout",
    // Auth translations
    auth: {
      login: {
        title: "Welcome back",
        subtitle: "Sign in to continue to PromptInk",
        emailLabel: "Email",
        emailPlaceholder: "Enter your email",
        passwordLabel: "Password",
        passwordPlaceholder: "Enter your password",
        loginButton: "Sign In",
        loggingIn: "Signing in...",
        noAccount: "Don't have an account?",
        signUp: "Sign up",
        forgotPassword: "Forgot password?",
      },
      register: {
        title: "Create account",
        subtitle: "Sign up to start creating images",
        nameLabel: "Name (optional)",
        namePlaceholder: "Enter your name",
        emailLabel: "Email",
        emailPlaceholder: "Enter your email",
        passwordLabel: "Password",
        passwordPlaceholder: "Create a password",
        confirmPasswordLabel: "Confirm Password",
        confirmPasswordPlaceholder: "Confirm your password",
        registerButton: "Create Account",
        registering: "Creating account...",
        hasAccount: "Already have an account?",
        signIn: "Sign in",
        passwordMismatch: "Passwords do not match",
        passwordTooShort: "Password must be at least 6 characters",
      },
    },
    settings: {
      title: "Settings",
      subtitle: "Configure your TRMNL device",
      deviceApiKeyLabel: "TRMNL Device API Key",
      deviceApiKeyPlaceholder: "Enter your device API key",
      macAddressLabel: "TRMNL MAC Address",
      macAddressPlaceholder: "e.g. 58:8C:81:A9:7D:14",
      backgroundColorLabel: "TRMNL Background Color",
      backgroundColorBlack: "Black",
      backgroundColorWhite: "White",
      saveButton: "Save Settings",
      saving: "Saving...",
      saveSuccess: "Settings saved successfully",
      saveError: "Failed to save settings",
      backToChat: "Back to Chat",
      webhookUrl: "Your TRMNL Webhook URL",
      webhookUrlNote: "Use this URL in your TRMNL plugin configuration",
      notConfigured: "Not configured",
    },
    subscription: {
      title: "Subscription",
      subtitle: "Manage your PromptInk subscription",
      plan: "Plan",
      planName: "PromptInk Monthly",
      price: "Price",
      priceValue: "$5.99/month",
      nextBillingDate: "Next billing date",
      totalOrders: "Total orders:",
      cancelSubscription: "Cancel Subscription",
      keepSubscription: "Keep Subscription",
      yesCancel: "Yes, Cancel",
      cancelConfirm: "Are you sure you want to cancel? You'll lose access at the end of your billing period.",
      cancelSuccess: "Subscription cancelled. You'll have access until the end of your billing period.",
      cancelError: "Failed to cancel subscription",
      reactivate: "Reactivate Subscription",
      reactivateError: "Failed to reactivate subscription",
      processing: "Processing...",
      purchaseToActivate: "Purchase a TRMNL Photo Frame to activate your subscription.",
      helpText: "Need help? Contact support@promptink.com",
      status: {
        none: {
          label: "No Subscription",
          description: "Purchase a photo frame to activate your subscription.",
        },
        active: {
          label: "Active",
          description: "Your subscription is active. Enjoy creating AI-powered images!",
        },
        paused: {
          label: "Paused",
          description: "Your subscription is paused. Resume to continue using the service.",
        },
        cancelled: {
          label: "Cancelled",
          description: "Your subscription has been cancelled. Reactivate to continue.",
        },
        past_due: {
          label: "Past Due",
          description: "Payment failed. Please update your payment method.",
        },
      },
    },
    orders: {
      title: "My Orders",
      orderCount: "{count} order",
      orderCountPlural: "{count} orders",
      orderMore: "Order More",
      orderNow: "Order Now",
      noOrdersTitle: "No orders yet",
      noOrdersDescription: "Get your first TRMNL Photo Frame to start creating AI-powered images.",
      goBack: "Go Back",
      orderNumber: "Order #{number}",
      placed: "Placed {date}",
      item: "item",
      items: "items",
      shippingTo: "Shipping to",
      tracking: "Tracking",
      trackPackage: "Track Package",
      giftFor: "Gift for {name}",
      paid: "Paid:",
      shipped: "Shipped:",
      delivered: "Delivered:",
      status: {
        pending: "Pending",
        paid: "Paid",
        processing: "Processing",
        shipped: "Shipped",
        delivered: "Delivered",
        cancelled: "Cancelled",
      },
    },
  },
  zh: {
    appName: "PromptInk",
    welcome: "您想创建什么图像？",
    welcomeSubtitle: "描述您的想法，我将使用 DALL-E 3 为您生成独特的图像",
    placeholder: "描述您想要创建的图像...",
    placeholderListening: "正在聆听...",
    generate: "生成",
    generating: "生成中...",
    generatingImage: "正在生成图像",
    newChat: "新对话",
    openFullSize: "查看原图",
    syncToTrmnl: "同步到 TRMNL",
    syncing: "同步中...",
    syncSuccess: "已同步！",
    footer: "PromptInk 使用 DALL-E 3 生成图像。按 Enter 发送，Shift+Enter 换行。",
    you: "你",
    assistant: "PromptInk",
    suggestions: [
      "夕阳下宁静的日式庭园，樱花盛开",
      "未来城市，飞行汽车穿梭，霓虹灯闪烁",
      "冬日山间温馨的小木屋",
      "海底宫殿，生物发光的奇幻生物环绕",
    ],
    errorPrefix: "错误：",
    defaultImageMessage: "这是为您生成的图像：",
    logout: "退出登录",
    // Auth translations
    auth: {
      login: {
        title: "欢迎回来",
        subtitle: "登录以继续使用 PromptInk",
        emailLabel: "邮箱",
        emailPlaceholder: "输入您的邮箱",
        passwordLabel: "密码",
        passwordPlaceholder: "输入您的密码",
        loginButton: "登录",
        loggingIn: "登录中...",
        noAccount: "还没有账户？",
        signUp: "注册",
        forgotPassword: "忘记密码？",
      },
      register: {
        title: "创建账户",
        subtitle: "注册以开始创建图像",
        nameLabel: "姓名（可选）",
        namePlaceholder: "输入您的姓名",
        emailLabel: "邮箱",
        emailPlaceholder: "输入您的邮箱",
        passwordLabel: "密码",
        passwordPlaceholder: "创建密码",
        confirmPasswordLabel: "确认密码",
        confirmPasswordPlaceholder: "确认您的密码",
        registerButton: "创建账户",
        registering: "创建中...",
        hasAccount: "已有账户？",
        signIn: "登录",
        passwordMismatch: "密码不匹配",
        passwordTooShort: "密码至少需要6个字符",
      },
    },
    settings: {
      title: "设置",
      subtitle: "配置您的 TRMNL 设备",
      deviceApiKeyLabel: "TRMNL 设备 API 密钥",
      deviceApiKeyPlaceholder: "输入您的设备 API 密钥",
      macAddressLabel: "TRMNL MAC 地址",
      macAddressPlaceholder: "例如 58:8C:81:A9:7D:14",
      backgroundColorLabel: "TRMNL 背景颜色",
      backgroundColorBlack: "黑色",
      backgroundColorWhite: "白色",
      saveButton: "保存设置",
      saving: "保存中...",
      saveSuccess: "设置保存成功",
      saveError: "保存设置失败",
      backToChat: "返回聊天",
      webhookUrl: "您的 TRMNL Webhook URL",
      webhookUrlNote: "在 TRMNL 插件配置中使用此 URL",
      notConfigured: "未配置",
    },
    subscription: {
      title: "订阅",
      subtitle: "管理您的 PromptInk 订阅",
      plan: "套餐",
      planName: "PromptInk 月度套餐",
      price: "价格",
      priceValue: "$5.99/月",
      nextBillingDate: "下次计费日期",
      totalOrders: "订单总数：",
      cancelSubscription: "取消订阅",
      keepSubscription: "保留订阅",
      yesCancel: "确认取消",
      cancelConfirm: "您确定要取消吗？您将在计费周期结束时失去访问权限。",
      cancelSuccess: "订阅已取消。您可以继续使用直到计费周期结束。",
      cancelError: "取消订阅失败",
      reactivate: "重新激活订阅",
      reactivateError: "重新激活订阅失败",
      processing: "处理中...",
      purchaseToActivate: "购买 TRMNL 相框以激活您的订阅。",
      helpText: "需要帮助？请联系 support@promptink.com",
      status: {
        none: {
          label: "无订阅",
          description: "购买相框以激活您的订阅。",
        },
        active: {
          label: "已激活",
          description: "您的订阅已激活。尽情创建 AI 图像吧！",
        },
        paused: {
          label: "已暂停",
          description: "您的订阅已暂停。恢复订阅以继续使用服务。",
        },
        cancelled: {
          label: "已取消",
          description: "您的订阅已取消。重新激活以继续使用。",
        },
        past_due: {
          label: "逾期未付",
          description: "付款失败。请更新您的付款方式。",
        },
      },
    },
    orders: {
      title: "我的订单",
      orderCount: "{count} 个订单",
      orderCountPlural: "{count} 个订单",
      orderMore: "再次订购",
      orderNow: "立即订购",
      noOrdersTitle: "暂无订单",
      noOrdersDescription: "购买您的第一个 TRMNL 相框，开始创建 AI 图像。",
      goBack: "返回",
      orderNumber: "订单 #{number}",
      placed: "下单于 {date}",
      item: "件商品",
      items: "件商品",
      shippingTo: "收货地址",
      tracking: "物流跟踪",
      trackPackage: "追踪包裹",
      giftFor: "礼物送给 {name}",
      paid: "已付款：",
      shipped: "已发货：",
      delivered: "已送达：",
      status: {
        pending: "待处理",
        paid: "已付款",
        processing: "处理中",
        shipped: "已发货",
        delivered: "已送达",
        cancelled: "已取消",
      },
    },
  },
}

export function useLanguage() {
  const [language, setLanguage] = useState<Language>(() => {
    if (typeof window !== "undefined") {
      const stored = localStorage.getItem("language") as Language
      if (stored) return stored
      // Detect browser language
      const browserLang = navigator.language.toLowerCase()
      if (browserLang.startsWith("zh")) return "zh"
    }
    return "en"
  })

  useEffect(() => {
    localStorage.setItem("language", language)
  }, [language])

  const toggleLanguage = () => {
    setLanguage((prev) => (prev === "en" ? "zh" : "en"))
  }

  const t = translations[language]

  return { language, toggleLanguage, t }
}
