import { useState, useEffect } from "react"

export type Language = "en" | "zh"

export const translations = {
  en: {
    appName: "PromptInk",
    welcome: "What image would you like to create?",
    welcomeSubtitle: "Describe your vision and I'll generate a unique image using DALL-E 3",
    placeholder: "Describe the image you want to create...",
    placeholderListening: "Listening...",
    generate: "Generate",
    generating: "Generating...",
    generatingImage: "Generating image",
    newChat: "New chat",
    openFullSize: "Open Full Size",
    syncToTrmnl: "Sync to TRMNL",
    syncing: "Syncing...",
    syncSuccess: "Synced!",
    share: "Share",
    sharing: "Creating link...",
    shareSuccess: "Link ready!",
    copyLink: "Copy",
    copied: "Copied!",
    close: "Close",
    footer: "PromptInk uses DALL-E 3 to generate images. Press Enter to send, Shift+Enter for new line.",
    you: "You",
    assistant: "PromptInk",
    suggestions: [
      "A serene Japanese garden with cherry blossoms at sunset",
      "A futuristic city with flying cars and neon lights",
      "A cozy cabin in the mountains during winter",
      "An underwater palace with bioluminescent creatures",
    ],
    refreshSuggestions: "Get new suggestions",
    imageSize: "Size",
    sizeSquare: "Square",
    sizeLandscape: "Landscape",
    sizePortrait: "Portrait",
    imageStyle: "Style",
    styleNone: "None",
    stylePhotorealistic: "Photorealistic",
    styleAnime: "Anime",
    styleWatercolor: "Watercolor",
    styleOilPainting: "Oil Painting",
    stylePixelArt: "Pixel Art",
    style3DRender: "3D Render",
    styleSketch: "Sketch",
    stylePopArt: "Pop Art",
    styleMinimalist: "Minimalist",
    styleCinematic: "Cinematic",
    errorPrefix: "Error:",
    defaultImageMessage: "Here's your generated image:",
    logout: "Logout",
    // Auth translations
    auth: {
      login: {
        title: "Welcome back",
        subtitle: "Sign in to continue to PromptInk",
        emailLabel: "Email",
        emailPlaceholder: "Enter your email",
        passwordLabel: "Password",
        passwordPlaceholder: "Enter your password",
        loginButton: "Sign In",
        loggingIn: "Signing in...",
        noAccount: "Don't have an account?",
        signUp: "Sign up",
        forgotPassword: "Forgot password?",
      },
      register: {
        title: "Create account",
        subtitle: "Sign up to start creating images",
        nameLabel: "Name (optional)",
        namePlaceholder: "Enter your name",
        emailLabel: "Email",
        emailPlaceholder: "Enter your email",
        passwordLabel: "Password",
        passwordPlaceholder: "Create a password",
        confirmPasswordLabel: "Confirm Password",
        confirmPasswordPlaceholder: "Confirm your password",
        registerButton: "Create Account",
        registering: "Creating account...",
        hasAccount: "Already have an account?",
        signIn: "Sign in",
        passwordMismatch: "Passwords do not match",
        passwordTooShort: "Password must be at least 6 characters",
      },
    },
    settings: {
      title: "Settings",
      subtitle: "Configure your TRMNL device",
      deviceApiKeyLabel: "TRMNL Device API Key",
      deviceApiKeyPlaceholder: "Enter your device API key",
      macAddressLabel: "TRMNL MAC Address",
      macAddressPlaceholder: "e.g. 58:8C:81:A9:7D:14",
      backgroundColorLabel: "TRMNL Background Color",
      backgroundColorBlack: "Black",
      backgroundColorWhite: "White",
      saveButton: "Save Settings",
      saving: "Saving...",
      saveSuccess: "Settings saved successfully",
      saveError: "Failed to save settings",
      backToChat: "Back to Chat",
      webhookUrl: "Your TRMNL Webhook URL",
      webhookUrlNote: "Use this URL in your TRMNL plugin configuration",
      notConfigured: "Not configured",
    },
    subscription: {
      title: "Subscription",
      subtitle: "Manage your PromptInk subscription",
      plan: "Plan",
      planName: "PromptInk Monthly",
      price: "Price",
      priceValue: "$6.53/month (incl. GST)",
      nextBillingDate: "Next billing date",
      totalOrders: "Total orders:",
      cancelSubscription: "Cancel Subscription",
      keepSubscription: "Keep Subscription",
      yesCancel: "Yes, Cancel",
      cancelConfirm: "Are you sure you want to cancel? You'll lose access at the end of your billing period.",
      cancelSuccess: "Subscription cancelled. You'll have access until the end of your billing period.",
      cancelError: "Failed to cancel subscription",
      reactivate: "Reactivate Subscription",
      reactivateError: "Failed to reactivate subscription",
      subscribeNow: "Subscribe Now",
      subscribeSuccess: "Subscription activated successfully!",
      subscribeError: "Failed to create subscription",
      alreadyOwnDevice: "Already own a TRMNL device? Subscribe to start creating AI images.",
      processing: "Processing...",
      purchaseToActivate: "Purchase a TRMNL Photo Frame to activate your subscription.",
      helpText: "Need help? Contact support@promptink.com",
      status: {
        none: {
          label: "No Subscription",
          description: "Purchase a photo frame to activate your subscription.",
        },
        active: {
          label: "Active",
          description: "Your subscription is active. Enjoy creating AI-powered images!",
        },
        paused: {
          label: "Paused",
          description: "Your subscription is paused. Resume to continue using the service.",
        },
        cancelled: {
          label: "Cancelled",
          description: "Your subscription has been cancelled. Reactivate to continue.",
        },
        past_due: {
          label: "Past Due",
          description: "Payment failed. Please update your payment method.",
        },
      },
    },
    orders: {
      title: "My Orders",
      orderCount: "{count} order",
      orderCountPlural: "{count} orders",
      orderMore: "Order More",
      orderNow: "Order Now",
      noOrdersTitle: "No orders yet",
      noOrdersDescription: "Get your first TRMNL Photo Frame to start creating AI-powered images.",
      goBack: "Go Back",
      orderNumber: "Order #{number}",
      placed: "Placed {date}",
      item: "item",
      items: "items",
      shippingTo: "Shipping to",
      tracking: "Tracking",
      trackPackage: "Track Package",
      giftFor: "Gift for {name}",
      paid: "Paid:",
      shipped: "Shipped:",
      delivered: "Delivered:",
      status: {
        pending: "Pending",
        paid: "Paid",
        processing: "Processing",
        shipped: "Shipped",
        delivered: "Delivered",
        cancelled: "Cancelled",
      },
    },
    purchase: {
      title: "TRMNL Photo Frame",
      subtitle: "AI-powered e-ink display for your space",
      pricePerFrame: "Price per frame",
      quantity: "Quantity",
      thisIsGift: "This is a gift",
      shippingAddress: "Shipping Address",
      fullName: "Full Name *",
      email: "Email (optional)",
      phone: "Phone Number *",
      addressLine1: "Address Line 1 *",
      addressLine2: "Address Line 2 (Apt, Suite, etc.)",
      city: "City *",
      state: "State *",
      postalCode: "Postal Code *",
      country: "Country *",
      giftDetails: "Gift Details",
      recipientName: "Recipient Name *",
      giftMessage: "Gift Message (optional)",
      subtotal: "Subtotal",
      frame: "frame",
      frames: "frames",
      monthlySubscription: "Monthly subscription",
      gst: "GST (9%)",
      inclGst: "incl. GST",
      totalToday: "Total today",
      subscriptionNote: "Subscription starts after your first purchase",
      pay: "Pay",
      processing: "Processing...",
      skipForNow: "Skip for now",
      securePayment: "Secure payment powered by Razorpay",
      errors: {
        fullName: "Please enter your full name",
        phone: "Please enter your phone number",
        address: "Please enter your address",
        city: "Please enter your city",
        state: "Please enter your state/province",
        postalCode: "Please enter your postal code",
        country: "Please enter your country",
        giftRecipient: "Please enter the gift recipient's name",
        paymentLoad: "Failed to load payment system. Please try again.",
        orderCreate: "Failed to create order",
        paymentVerify: "Payment verification failed",
        general: "An error occurred",
      },
    },
    gallery: {
      title: "Image Gallery",
      totalImages: "{count} images",
      totalFavorites: "{count} favorites",
      refresh: "Refresh",
      upload: "Upload",
      uploading: "Uploading...",
      uploadSuccess: "Image uploaded successfully",
      back: "Back",
      allImages: "All Images",
      favorites: "Favorites",
      searchPlaceholder: "Search by prompt...",
      searchingFor: "Searching for",
      clearSearch: "Clear",
      noSearchResults: "No images found",
      tryDifferentSearch: "Try a different search term or check your filters.",
      noFavorites: "No favorites yet",
      noFavoritesHint: "Star images to add them to your favorites.",
      noImages: "No images yet",
      noImagesHint: "Generate your first image to start building your gallery.",
      viewAllImages: "View All Images",
      loading: "Loading...",
      loadMore: "Load More",
      remaining: "remaining",
      tryAgain: "Try Again",
      confirmDelete: "Are you sure you want to delete this image?",
      edited: "Edited",
      previous: "Previous",
      next: "Next",
      close: "Close",
      favorite: "Favorite",
      unfavorite: "Remove from favorites",
      addFavorite: "Add to favorites",
      download: "Download",
      exporting: "Exporting...",
      exportBestQuality: "Best quality",
      exportSmaller: "Smaller file",
      exportSmallest: "Smallest file",
      delete: "Delete",
      prompt: "Prompt",
      revisedPrompt: "Revised Prompt",
      model: "Model",
      size: "Size",
      style: "Style",
      created: "Created",
    },
    schedule: {
      title: "Schedule",
      description: "Automatically generate images on a schedule",
      newSchedule: "New Schedule",
      createSchedule: "Create Schedule",
      editSchedule: "Edit Schedule",
      scheduleType: "Schedule Type",
      once: "Once",
      daily: "Daily",
      weekly: "Weekly",
      scheduleTime: "Time",
      scheduleDays: "Days",
      scheduledAt: "Date & Time",
      autoSyncTrmnl: "Auto-sync to TRMNL display",
      nextRun: "Next run",
      overdue: "Overdue",
      soon: "Soon",
      runs: "runs",
      schedulesUsed: "schedules",
      noSchedules: "No scheduled jobs yet",
      createFirstSchedule: "Create your first schedule to get started",
      confirmDelete: "Delete this schedule?",
      update: "Update",
      create: "Create",
      cancel: "Cancel",
      delete: "Delete",
      prompt: "Prompt",
      enterPrompt: "Enter your image prompt...",
    },
    batch: {
      title: "Batch",
      description: "Generate multiple images at once",
      newBatch: "New Batch",
      createBatch: "Create Batch Job",
      batchName: "Batch Name (Optional)",
      batchNamePlaceholder: "e.g., Nature scenes",
      prompts: "Prompts",
      addPrompt: "Add",
      startBatch: "Start Batch",
      pending: "Pending",
      processing: "Processing",
      completed: "Completed",
      failed: "Failed",
      cancelled: "Cancelled",
      progress: "Progress",
      complete: "complete",
      images: "Images",
      total: "Total",
      status: "Status",
      created: "Created",
      noBatches: "No batch jobs yet",
      createBatchHint: "Create a batch to generate multiple images at once",
      confirmCancelBatch: "Are you sure you want to cancel this batch?",
      confirmDeleteBatch: "Are you sure you want to delete this batch?",
      oneBatchProcessing: "1 batch is being processed...",
      batchesProcessing: "batches are being processed...",
    },
  },
  zh: {
    appName: "PromptInk",
    welcome: "您想创建什么图像？",
    welcomeSubtitle: "描述您的想法，我将使用 DALL-E 3 为您生成独特的图像",
    placeholder: "描述您想要创建的图像...",
    placeholderListening: "正在聆听...",
    generate: "生成",
    generating: "生成中...",
    generatingImage: "正在生成图像",
    newChat: "新对话",
    openFullSize: "查看原图",
    syncToTrmnl: "同步到 TRMNL",
    syncing: "同步中...",
    syncSuccess: "已同步！",
    share: "分享",
    sharing: "创建链接...",
    shareSuccess: "链接已就绪！",
    copyLink: "复制",
    copied: "已复制！",
    close: "关闭",
    footer: "PromptInk 使用 DALL-E 3 生成图像。按 Enter 发送，Shift+Enter 换行。",
    you: "你",
    assistant: "PromptInk",
    suggestions: [
      "夕阳下宁静的日式庭园，樱花盛开",
      "未来城市，飞行汽车穿梭，霓虹灯闪烁",
      "冬日山间温馨的小木屋",
      "海底宫殿，生物发光的奇幻生物环绕",
    ],
    refreshSuggestions: "获取新建议",
    imageSize: "尺寸",
    sizeSquare: "方形",
    sizeLandscape: "横版",
    sizePortrait: "竖版",
    imageStyle: "风格",
    styleNone: "无",
    stylePhotorealistic: "写实",
    styleAnime: "动漫",
    styleWatercolor: "水彩",
    styleOilPainting: "油画",
    stylePixelArt: "像素",
    style3DRender: "3D渲染",
    styleSketch: "素描",
    stylePopArt: "波普",
    styleMinimalist: "极简",
    styleCinematic: "电影",
    errorPrefix: "错误：",
    defaultImageMessage: "这是为您生成的图像：",
    logout: "退出登录",
    // Auth translations
    auth: {
      login: {
        title: "欢迎回来",
        subtitle: "登录以继续使用 PromptInk",
        emailLabel: "邮箱",
        emailPlaceholder: "输入您的邮箱",
        passwordLabel: "密码",
        passwordPlaceholder: "输入您的密码",
        loginButton: "登录",
        loggingIn: "登录中...",
        noAccount: "还没有账户？",
        signUp: "注册",
        forgotPassword: "忘记密码？",
      },
      register: {
        title: "创建账户",
        subtitle: "注册以开始创建图像",
        nameLabel: "姓名（可选）",
        namePlaceholder: "输入您的姓名",
        emailLabel: "邮箱",
        emailPlaceholder: "输入您的邮箱",
        passwordLabel: "密码",
        passwordPlaceholder: "创建密码",
        confirmPasswordLabel: "确认密码",
        confirmPasswordPlaceholder: "确认您的密码",
        registerButton: "创建账户",
        registering: "创建中...",
        hasAccount: "已有账户？",
        signIn: "登录",
        passwordMismatch: "密码不匹配",
        passwordTooShort: "密码至少需要6个字符",
      },
    },
    settings: {
      title: "设置",
      subtitle: "配置您的 TRMNL 设备",
      deviceApiKeyLabel: "TRMNL 设备 API 密钥",
      deviceApiKeyPlaceholder: "输入您的设备 API 密钥",
      macAddressLabel: "TRMNL MAC 地址",
      macAddressPlaceholder: "例如 58:8C:81:A9:7D:14",
      backgroundColorLabel: "TRMNL 背景颜色",
      backgroundColorBlack: "黑色",
      backgroundColorWhite: "白色",
      saveButton: "保存设置",
      saving: "保存中...",
      saveSuccess: "设置保存成功",
      saveError: "保存设置失败",
      backToChat: "返回聊天",
      webhookUrl: "您的 TRMNL Webhook URL",
      webhookUrlNote: "在 TRMNL 插件配置中使用此 URL",
      notConfigured: "未配置",
    },
    subscription: {
      title: "订阅",
      subtitle: "管理您的 PromptInk 订阅",
      plan: "套餐",
      planName: "PromptInk 月度套餐",
      price: "价格",
      priceValue: "$6.53/月 (含消费税)",
      nextBillingDate: "下次计费日期",
      totalOrders: "订单总数：",
      cancelSubscription: "取消订阅",
      keepSubscription: "保留订阅",
      yesCancel: "确认取消",
      cancelConfirm: "您确定要取消吗？您将在计费周期结束时失去访问权限。",
      cancelSuccess: "订阅已取消。您可以继续使用直到计费周期结束。",
      cancelError: "取消订阅失败",
      reactivate: "重新激活订阅",
      reactivateError: "重新激活订阅失败",
      subscribeNow: "立即订阅",
      subscribeSuccess: "订阅激活成功！",
      subscribeError: "创建订阅失败",
      alreadyOwnDevice: "已有 TRMNL 设备？订阅即可开始创建 AI 图像。",
      processing: "处理中...",
      purchaseToActivate: "购买 TRMNL 相框以激活您的订阅。",
      helpText: "需要帮助？请联系 support@promptink.com",
      status: {
        none: {
          label: "无订阅",
          description: "购买相框以激活您的订阅。",
        },
        active: {
          label: "已激活",
          description: "您的订阅已激活。尽情创建 AI 图像吧！",
        },
        paused: {
          label: "已暂停",
          description: "您的订阅已暂停。恢复订阅以继续使用服务。",
        },
        cancelled: {
          label: "已取消",
          description: "您的订阅已取消。重新激活以继续使用。",
        },
        past_due: {
          label: "逾期未付",
          description: "付款失败。请更新您的付款方式。",
        },
      },
    },
    orders: {
      title: "我的订单",
      orderCount: "{count} 个订单",
      orderCountPlural: "{count} 个订单",
      orderMore: "再次订购",
      orderNow: "立即订购",
      noOrdersTitle: "暂无订单",
      noOrdersDescription: "购买您的第一个 TRMNL 相框，开始创建 AI 图像。",
      goBack: "返回",
      orderNumber: "订单 #{number}",
      placed: "下单于 {date}",
      item: "件商品",
      items: "件商品",
      shippingTo: "收货地址",
      tracking: "物流跟踪",
      trackPackage: "追踪包裹",
      giftFor: "礼物送给 {name}",
      paid: "已付款：",
      shipped: "已发货：",
      delivered: "已送达：",
      status: {
        pending: "待处理",
        paid: "已付款",
        processing: "处理中",
        shipped: "已发货",
        delivered: "已送达",
        cancelled: "已取消",
      },
    },
    purchase: {
      title: "TRMNL 相框",
      subtitle: "AI 驱动的电子墨水显示屏",
      pricePerFrame: "单价",
      quantity: "数量",
      thisIsGift: "这是一份礼物",
      shippingAddress: "收货地址",
      fullName: "姓名 *",
      email: "邮箱（可选）",
      phone: "电话号码 *",
      addressLine1: "地址行 1 *",
      addressLine2: "地址行 2（公寓、套房等）",
      city: "城市 *",
      state: "省份 *",
      postalCode: "邮政编码 *",
      country: "国家 *",
      giftDetails: "礼物详情",
      recipientName: "收礼人姓名 *",
      giftMessage: "礼物留言（可选）",
      subtotal: "小计",
      frame: "个相框",
      frames: "个相框",
      monthlySubscription: "月度订阅",
      gst: "消费税 (9%)",
      inclGst: "含消费税",
      totalToday: "今日总计",
      subscriptionNote: "首次购买后开始订阅",
      pay: "支付",
      processing: "处理中...",
      skipForNow: "暂时跳过",
      securePayment: "由 Razorpay 提供安全支付",
      errors: {
        fullName: "请输入您的姓名",
        phone: "请输入您的电话号码",
        address: "请输入您的地址",
        city: "请输入您的城市",
        state: "请输入您的省份",
        postalCode: "请输入您的邮政编码",
        country: "请输入您的国家",
        giftRecipient: "请输入收礼人姓名",
        paymentLoad: "加载支付系统失败，请重试。",
        orderCreate: "创建订单失败",
        paymentVerify: "支付验证失败",
        general: "发生错误",
      },
    },
    gallery: {
      title: "图片库",
      totalImages: "{count} 张图片",
      totalFavorites: "{count} 个收藏",
      refresh: "刷新",
      upload: "上传",
      uploading: "上传中...",
      uploadSuccess: "图片上传成功",
      back: "返回",
      allImages: "全部图片",
      favorites: "收藏",
      searchPlaceholder: "搜索提示词...",
      searchingFor: "正在搜索",
      clearSearch: "清除",
      noSearchResults: "未找到图片",
      tryDifferentSearch: "尝试不同的搜索词或检查筛选条件。",
      noFavorites: "暂无收藏",
      noFavoritesHint: "点击星标将图片添加到收藏。",
      noImages: "暂无图片",
      noImagesHint: "生成您的第一张图片，开始建立您的图库。",
      viewAllImages: "查看全部图片",
      loading: "加载中...",
      loadMore: "加载更多",
      remaining: "剩余",
      tryAgain: "重试",
      confirmDelete: "确定要删除这张图片吗？",
      edited: "已编辑",
      previous: "上一张",
      next: "下一张",
      close: "关闭",
      favorite: "已收藏",
      unfavorite: "取消收藏",
      addFavorite: "添加收藏",
      download: "下载",
      exporting: "导出中...",
      exportBestQuality: "最佳质量",
      exportSmaller: "较小文件",
      exportSmallest: "最小文件",
      delete: "删除",
      prompt: "提示词",
      revisedPrompt: "优化后的提示词",
      model: "模型",
      size: "尺寸",
      style: "风格",
      created: "创建时间",
    },
    schedule: {
      title: "定时任务",
      description: "按计划自动生成图片",
      newSchedule: "新建任务",
      createSchedule: "创建任务",
      editSchedule: "编辑任务",
      scheduleType: "计划类型",
      once: "一次性",
      daily: "每天",
      weekly: "每周",
      scheduleTime: "时间",
      scheduleDays: "日期",
      scheduledAt: "日期和时间",
      autoSyncTrmnl: "自动同步到 TRMNL 显示屏",
      nextRun: "下次运行",
      overdue: "已过期",
      soon: "即将",
      runs: "次运行",
      schedulesUsed: "个任务",
      noSchedules: "暂无定时任务",
      createFirstSchedule: "创建您的第一个定时任务开始使用",
      confirmDelete: "确定删除此任务？",
      update: "更新",
      create: "创建",
      cancel: "取消",
      delete: "删除",
      prompt: "提示词",
      enterPrompt: "输入您的图片提示词...",
    },
    batch: {
      title: "批量生成",
      description: "一次生成多张图片",
      newBatch: "新建批量",
      createBatch: "创建批量任务",
      batchName: "批量名称（可选）",
      batchNamePlaceholder: "例如：自然风景",
      prompts: "提示词",
      addPrompt: "添加",
      startBatch: "开始批量生成",
      pending: "等待中",
      processing: "处理中",
      completed: "已完成",
      failed: "失败",
      cancelled: "已取消",
      progress: "进度",
      complete: "完成",
      images: "图片",
      total: "总计",
      status: "状态",
      created: "创建时间",
      noBatches: "暂无批量任务",
      createBatchHint: "创建批量任务一次生成多张图片",
      confirmCancelBatch: "确定要取消此批量任务吗？",
      confirmDeleteBatch: "确定要删除此批量任务吗？",
      oneBatchProcessing: "1 个批量任务正在处理中...",
      batchesProcessing: "个批量任务正在处理中...",
    },
  },
}

export function useLanguage() {
  const [language, setLanguage] = useState<Language>(() => {
    if (typeof window !== "undefined") {
      const stored = localStorage.getItem("language") as Language
      if (stored) return stored
      // Detect browser language
      const browserLang = navigator.language.toLowerCase()
      if (browserLang.startsWith("zh")) return "zh"
    }
    return "en"
  })

  useEffect(() => {
    localStorage.setItem("language", language)
  }, [language])

  const toggleLanguage = () => {
    setLanguage((prev) => (prev === "en" ? "zh" : "en"))
  }

  const t = translations[language]

  return { language, toggleLanguage, t }
}
